### ISSUE TITLE
How to deserialize certs endpoint in Keycloak?

### ISSUE THREAD

**Issue by SamTV12345** [Keats/jsonwebtoken#306] opened 2023-04-03 12:25 UTC
I have the problem that one algorithm in the certs endpoint is not recognized by your library. Could you please give a sample on how to get around this? I am fine with RS256 algorithm I just need to get rid of RSA-OAEP that is also deserialized from serde.

**Comment by Keats** [comment] 2023-04-03 20:14
Duplicate of https://github.com/Keats/jsonwebtoken/issues/252

**Closed by Keats** 2023-04-03 20:14 UTC

**Comment by SamTV12345** [comment] 2023-04-03 20:50
Found it out on my own. Just create a new model, drop everything that is not RSA256 and then serialize and deserialize it.
